# Use ASV to check performance reqressions in the last 24 hours' commits.

name: benchmark-check

on:
  pull_request:
    #only_if: ${SKIP_BENCHMARK_TASK} == ""
  push:
    branches:
      - "main"
      - "v*x"
      - "!auto-update-lockfiles"
      - "!pre-commit-ci-update-config"
      - "!dependabot/*"
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: "performance benchmarks (py${{ matrix.python-version }} ${{ matrix.os }}"

    runs-on: ubuntu-latest

    env:
      PY_VER: "3.10"
      IRIS_TEST_DATA_LOC_PATH: benchmarks
      IRIS_TEST_DATA_PATH: benchmarks/iris-test-data
      IRIS_TEST_DATA_VERSION: "2.19"
      IRIS_SOURCE: "github:main"
      ENV_CACHE_BUILD: "0"
      TEST_DATA_CACHE_BUILD: "0"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - run: git checkout HEAD^2

      - name: Install ASV & Nox
        run: |
          pip install asv nox

      - name: Cache environment directories
        uses: actions/cache@v3
        with:
          path: |
            .nox
            benchmarks/.asv/env
            $CONDA/pkgs
          key: ${{ runner.os }}-${{ hashFiles('requirements/') }}-${{ env.ENV_CACHE_BUILD }}-${{ env.IRIS_SOURCE }}

      - name: Benchmark script
        run: |
          if ${{ github.event_name != 'pull_request' }}; then export COMPARE="HEAD~"; else export COMPARE="origin/${{ github.base_ref }}"; fi;
          nox --session=tests --install-only
          export DATA_GEN_PYTHON=$(realpath $(find .nox -path "*tests/bin/python"))
          nox --session="benchmarks(branch)" -- "${COMPARE}"

      - name: Archive ASV results
        uses: actions/upload-artifact@v3
        with:
          name: asv-report
          path: |
            benchmarks/.asv/results
