# reference:
#   - https://github.com/actions/cache
#   - https://github.com/actions/checkout

name: ci-tests

on:
  pull_request:

  push:
    branches:
      - "main"
      - "v*x"
      - "!auto-update-lockfiles"
      - "!pre-commit-ci-update-config"
      - "!dependabot/*"
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "${{ matrix.session }} (py${{ matrix.python-version }} ${{ matrix.os }})"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    env:
      ENV_NAME: "ci-tests"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["38", "39", "310"]
        session: ["tests"]
        include:
          - python-version: "310"
            cov-report: "--cov-report=xml --cov"
            codecov: "codecov"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "conda-forge setup (python ${{ matrix.python-version }})"
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          channels: conda-forge,defaults
          channel-priority: true
          auto-update-conda: true
          environment-file: "requirements/locks/py${{ matrix.python-version }}-linux-64.lock"
          activate-environment: ${{ env.ENV_NAME }}

      - name: "tests (py${{ matrix.python-version }})"
        run: |
          python -m pip install --no-deps --editable .
          pytest ${{ matrix.cov-report }}
          ${{ matrix.codecov }}
